### ISSUE TITLE
Request to PGS failed because all packs are unavailable

### ISSUE THREAD

**Issue by youZhuang** [Unity-Technologies/Addressables-Sample#81]
Hi,
I follow the sample to integrate play asset Delivery. And upload to play store. I got some error log just like below when I launch game which is download from google play store. Is something wrong?

Unity version 2021.3.12f1
Addressables version : 1.19.19
Play core : 1.7.0

`Finsky  : [77377] gxs.a(8): Request execution failed with error code: -2
12-08 18:54:21.134  5920 15353 E Finsky  : com.google.android.finsky.assetmoduleserviceutils.AssetModuleException: Request to PGS failed because all packs are unavailable.
12-08 18:54:21.134  5920 15353 E Finsky  : 	at hhp.hr(Unknown Source:4)
12-08 18:54:21.134  5920 15353 E Finsky  : 	at fhr.q(Unknown Source:55)
12-08 18:54:21.134  5920 15353 E Finsky  : 	at dhn.run(PG:2)
12-08 18:54:21.134  5920 15353 E Finsky  : 	at android.os.Handler.handleCallback(Handler.java:914)
12-08 18:54:21.134  5920 15353 E Finsky  : 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-08 18:54:21.134  5920 15353 E Finsky  : 	at android.os.Looper.loop(Looper.java:224)
12-08 18:54:21.134  5920 15353 E Finsky  : 	at android.app.ActivityThread.main(ActivityThread.java:7560)
12-08 18:54:21.134  5920 15353 E Finsky  : 	at java.lang.reflect.Method.invoke(Native Method)
12-08 18:54:21.134  5920 15353 E Finsky  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
12-08 18:54:21.134  5920 15353 E Finsky  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
12-08 18:54:21.137 15265 15333 V FA      : Connection attempt already in progress
12-08 18:54:21.137 15265 15333 V FA      : Connection attempt already in progress
12-08 18:54:21.137 15265 15341 I PlayCore: UID: [12009]  PID: [15265] AssetPackServiceImpl : Leaving the connection open for other ongoing calls.
12-08 18:54:21.137 15265 15333 D FA      : Connected to remote service
12-08 18:54:21.137 15265 15341 E PlayCore: UID: [12009]  PID: [15265] AssetPackServiceImpl : onError(-2)
12-08 18:54:21.138 15265 15333 V FA      : Processing queued up service tasks: 7
12-08 18:54:21.138 15265 15349 I PlayCore: UID: [12009]  PID: [15265] AssetPackServiceImpl : getChunkFileDescriptor(CustomFastFollow, CustomFastFollow, 0, session=47)
12-08 18:54:21.139  5920  5939 I Finsky  : [77086] hec.h(2): getChunkFileDescriptor for package: com.joypoppuzzle.homeblock, chunkId: AssetModuleChunkId{sessionId=47, moduleName=CustomFastFollow, sliceId=CustomFastFollow, chunkIndex=0}`

**Comment by mtemnikov** [comment]
The same issue here on Unity version 2021.3.28f1
